pipeline {
    agent any

    tools {nodejs "NodeJS"}

    environment {
        PROJECT_PATH="/Users/nutthawutkorkedbun/Dev/repo/training/devops-onboarding/testing-strategy-3"
        // PROJECT_PATH="${env.JENKINS_HOME}/workspace/OnBoardingPart3/testing-strategy-3"
        SCRIPTS_PATH="${PROJECT_PATH}/scripts"
        DEV="dev"
        ALPHA="alpha"
        PREPROD="preprod"
        PROD="prod"
    }

    stages {
        stage('Build') {
           steps {
                dir("${SCRIPTS_PATH}") {
                    sh """
                    sh application-management.sh build
                    sh application-management.sh start &
                    """
                }
            }
        }
        stage('Test environment DEV') {
            steps {
                dir("${SCRIPTS_PATH}") {
                   sh """
                    sh report.sh test local
                    sh report.sh generate local
                    """
                }
            }
        }
        stage('Deployment') {
            steps {
                dir("${SCRIPTS_PATH}") {
                   sh """
                    echo "Deployment"
                    """
                }
            }
        }
    }
    post {
        always {
            dir("${SCRIPTS_PATH}") {
                sh """
                sh application-management.sh close
                sh report.sh clean local
                """
                publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: '../e2e-web/cypress/cucumber-json/', reportFiles: 'index.html', reportName: 'Test Report', reportTitles: '', useWrapperFileDirectly: true])
            }
        }
    }
}